theme: minima
title: Clubul Sportiv ShiTeiDoKo
description: Clubul Sportiv ShiTeiDoko

header_pages:
  - index.md
  - about.md
  - ju-jitsu.md
  - program.md
  - comunitate.md
  - media.md
  - documents.md
  - contact.md
