theme: minima
skin: dark
title: ShiTeiDoko
description: Clubul Sportiv ShiTeiDoko

header_pages:
  - despre.md
  - video.md
  - foto.md
  - program.md
  - documente.md
  - contact.md

social_links:
  - title: "Clubul Sportiv ShiTeiDoko facebook"
    icon: facebook
    url: "https://www.facebook.com/shiteidoko"
  - title: "Jekyll at X (formerly Twitter)"
    icon: x-twitter
    url: "https://x.com/jekyllrb"